### ISSUE TITLE
Maximum Call Stack Size Exceeded

### ISSUE THREAD

**Issue by suggested-username** [Kaseaa/tera-guide#15]
`[21:54:54.685] RangeError: Maximum call stack size exceeded<br>
    at Function.assign (<anonymous>)
    at MigrateSettings (C:\Users\Admin\Desktop\TeraToolbox\mods\tera-guide\settings_migrator.js:40:35)
    at MigrateSettings (C:\Users\Admin\Desktop\TeraToolbox\mods\tera-guide\settings_migrator.js:29:24)
    at MigrateSettings (C:\Users\Admin\Desktop\TeraToolbox\mods\tera-guide\settings_migrator.js:30:20)<
    at MigrateSettings (C:\Users\Admin\Desktop\TeraToolbox\mods\tera-guide\settings_migrator.js:30:20)
    at MigrateSettings (C:\Users\Admin\Desktop\TeraToolbox\mods\tera-guide\settings_migrator.js:30:20)
    at MigrateSettings (C:\Users\Admin\Desktop\TeraToolbox\mods\tera-guide\settings_migrator.js:30:20)
    at MigrateSettings (C:\Users\Admin\Desktop\TeraToolbox\mods\tera-guide\settings_migrator.js:30:20)
    at MigrateSettings (C:\Users\Admin\Desktop\TeraToolbox\mods\tera-guide\settings_migrator.js:30:20)
    at MigrateSettings (C:\Users\Admin\Desktop\TeraToolbox\mods\tera-guide\settings_migrator.js:30:20)`

**Comment by suggested-username** [comment]
nevermind. I'm an idiot
